version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    user: root
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      LOG_DIR: /var/log/zookeeper
      ZOOKEEPER_DATA_DIR: /var/lib/zookeeper
    ports:
      - 2181:2181
    volumes:
      - /home/zookeeper/data:/var/lib/zookeeper/data
      - /home/zookeeper/logLib:/var/lib/zookeeper/log
      - /home/zookeeper/log:/var/log/zookeeper
  
  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: kafka
    user: root
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      LOG_DIR: /var/log/kafka
      KAFKA_DATA_DIR: /var/lib/kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092,PLAINTEXT_HOST://127.0.0.1:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /home/kafka/data:/var/lib/kafka/data
      - /home/kafka/log:/var/log/kafka